### ISSUE TITLE
Animation dons't work

### ISSUE THREAD

**Issue by grabit** [forrestkirby/counter-element#1]
I can't animate the counter

Have a look: https://bir.grab-it.com/the-industry

Using YTP 1.21.5 this element doesn't animate and I can't set the maximum.

Your progress element is working fine

**Comment by forrestkirby** [comment]
This seems to happen when there is an animation on the element. As a workaround, set *Animation* to `None` for the element. I will have to check whether I can make both work together the element animation and the count up animation. Thanks for reporting.

**Comment by grabit** [comment]
Indeed it work when I do what you suggest.

Now I see another problem, when counting, the text is giggling on the second and third line with some settings and not with others.
--
Jean Hins 
Grab it
107 rue Coosemans - 1030 Brussels - Belgium
Phone: +32 2 737 91 11
e-mail: jean@grab-it.com

An apple a day keeps the doctor away


Le 17 juil. 2019 à 17:41, forrestkirby <notifications@github.com> a écrit :

This seems to happen when there is an animation on the element. As a workaround, set Animation to None for the element. I will have to check whether I can make both work together the element animation and the count up animation. Thanks for reporting.

**Comment by forrestkirby** [comment]
Please see [Counter animation wobbling](https://github.com/forrestkirby/counter-element/issues/2)

**Comment by forrestkirby** [comment]
Please try the change in #4. It should fix the animation issue. If you can confirm animations are working now, I will commit the change to the master branch.

**Comment by grabit** [comment]
It seems to work fine with that file
--
Jean Hins 
Grab it
107 rue Coosemans - 1030 Brussels - Belgium
Phone: +32 2 737 91 11
e-mail: jean@grab-it.com

An apple a day keeps the doctor away


Le 18 juil. 2019 à 20:55, forrestkirby <notifications@github.com> a écrit :

Can you please try replacing the file yootheme_child/builder/hd-counter/js/counter.js by the one in branch #3 <https://github.com/forrestkirby/counter-element/pull/3>? This should fix the issue. If you can confirm animations are working now, I will commit the change to the master branch.
