### ISSUE TITLE
Animated circle stopped working

### ISSUE THREAD

**Issue by sevenbe8** [forrestkirby/counter-element#13]
Hi there, 

I've just updated to the latest version of yootheme, wordpress and hd counter, but the animated circles are not working. 
Could you please possibly have a look?

https://elaghmore.com

At the bottom... 

Kindest regards
Regine

**Comment by forrestkirby** [comment]
Hi Regine,

I see the issue on your site, but I could not reproduce it. On your site, the JS file `/wp-content/themes/yootheme-elaghmore/builder/hd-counter/js/hd-counter.js?ver=2.2.4` is not being loaded. This file is necessary for the count-up animation to work. As a workaround, you could try to load the file via a script tag in your HTML document.

Regards
Thomas

**Comment by sevenbe8** [comment]
Hi Thomas, 


Thank you so much for looking at this. 
Could you please explain how I do the workaround? 
I am no techie, just a designer. ;-)


Kindest regards
Regine




  
  
  



Essence  | Brand Strategy and Design
26 College Hill, Sutton Coldfield B73 6HA



Mob 07940 564849 | www.essence-design.co.uk


Read our Blog
 | Find me on LinkedIn

**Comment by forrestkirby** [comment]
Hi Regine,

one way would be to add an HTML element to the layout with the counter element. The HTML element must be placed anywhere *after* the counter element. If you have multiple counter elements in your layout, add only *one* HTML element anywhere *after* the last counter element. Into the content field of the HTML element paste the following

```
<script src="wp-content/themes/yootheme-child/builder/hd-counter/js/hd-counter.js"></script>
```

You can check whether the file has been loaded in the *Sources* tab of your browser developer tools.

![](https://pionte.ch/yootheme/max/images/2020-09-05_110156.jpg)

---

Note that there is a JavaScript error on the site you linked in the cached/minified file `https://elaghmore.com/wp-content/cache/min/1/fa00e851bf82ee3e3ae83c27d97220e0.js:22`. This is not related to the counter element, though.

```
Uncaught TypeError: Cannot read property 'once' of undefined
    at fa00e851bf82ee3e3ae83c27d97220e0.js:22
    at t (fa00e851bf82ee3e3ae83c27d97220e0.js:25)
    at fa00e851bf82ee3e3ae83c27d97220e0.js:25
    at Object.pe [as ready] (fa00e851bf82ee3e3ae83c27d97220e0.js:23)
    at fa00e851bf82ee3e3ae83c27d97220e0.js:25
    at fa00e851bf82ee3e3ae83c27d97220e0.js:25
```

Regards
Thomas

**Comment by sevenbe8** [comment]
Thanks Thomas, 


I believe I’ve done that, but nothing has changed? 
Is there something else I need to do? 


Thanks 
Regine




  
  
  



Essence  | Brand Strategy and Design
26 College Hill, Sutton Coldfield B73 6HA



Mob 07940 564849 | www.essence-design.co.uk


Read our Blog
 | Find me on LinkedIn

**Comment by forrestkirby** [comment]
Please change the path to the JavaScript file to match your child theme path, else the file can’t be found. So replace `yootheme-child` by `yootheme-elaghmore` or whatever your child theme is called.

```
<script src="wp-content/themes/yootheme-elaghmore/builder/hd-counter/js/hd-counter.js"></script>
```

![](https://pionte.ch/yootheme/max/images/2020-09-05_122649.jpg)

**Comment by sevenbe8** [comment]
Perfect! Thank you so much. 


Have a lovely weekend! 
Regine




  
  
  



Essence  | Brand Strategy and Design
26 College Hill, Sutton Coldfield B73 6HA



Mob 07940 564849 | www.essence-design.co.uk


Read our Blog
 | Find me on LinkedIn

**Comment by sevenbe8** [comment]
Sorry Thomas,

I’ve just tested it on mobile and the issue is still there? Does mobile need a different bit of code? Can you perhaps see on your mobile why it happens? 

Thank you
Regine 

>

**Comment by forrestkirby** [comment]
Hi Regine,

there is no difference for desktop or mobile in the workaround mentioned above. In the source code of your website, there is no `<script>` tag that includes the script I mentioned. Assuming you actually added the HTML element as described, you should check that you don’t use an editor that removes certain tags for security reasons and that you don’t have some kind of optimization or output manipulation plugin or script that removes the content of that HTML element.

Regards
Thomas
