### ISSUE TITLE
installed the element, see it as available, unable to insert it on the page

### ISSUE THREAD

**Issue by elipritykin** [forrestkirby/counter-element#15]
I just uploaded the HD Counter element (https://github.com/forrestkirby/counter-element) to my website, under the child theme. It shows up in the list of elements, but when I click on it nothing happens. It doens't get added to the page. This is not an issue with any other elements.

I've also previously added the HD Timeline element successfully, and am able to use it with no issues.

**Comment by forrestkirby** [comment]
Hi elipritykin,

I could not reproduce this issue. Make sure you are using the latest version of both YOOtheme Pro and the Counter element and that the counter element files are stored at `/templates/yootheme_child/builder/hd-counter/` (Joomla!) or `/wp-content/themes/yootheme-child/builder/hd-counter/` (WordPress) (and not `/templates/yootheme_child/builder/counter-element-master/hd-counter/` or anything similar).

Regards
Thomas

**Comment by elipritykin** [comment]
Yes, I'm not sure where the snag is. I have the files in wp-content/themes/orgname-yootheme-child/builder/hd-counter

The element shows up when I bring up the "add element" interface.
I've also successfully added the hd-timeline element in the same fashion, and it is working correctly.

I checked permissions etc. Mystery.

**Comment by forrestkirby** [comment]
> I have the files in wp-content/themes/orgname-yootheme-child/builder/hd-counter

I just tested this with no additional files, only the `style.css` of the child theme and the `builder/hd-counter/` directory and files. The counter element appeared just fine. Maybe you could try a hard refresh on the browser cache and, if you have any other files like layout overrides, temporarily test without these to make sure there’s no interference. Anyways, I could not see any issue with the element in general here.

**Comment by forrestkirby** [comment]
closed due to inactivity
