### ISSUE TITLE
i can not see the counter element inside builder

### ISSUE THREAD

**Issue by javier940** [forrestkirby/counter-element#16]
i create the directory   yootheme_child
i create the folder yootheme_child/builder
i put inside the folder and archives from hd
i activate in settings the child theme
in the builder i can not see nothing new

**Comment by forrestkirby** [comment]
Hi javier940,

I could not reproduce this issue. Make sure you are using the latest version of both YOOtheme Pro and the Counter element and that the counter element files are stored at `/templates/yootheme_child/builder/hd-counter/` (and not `/templates/yootheme_child/builder/counter-element-master` or anything similar).

Regards
Thomas

**Comment by javier940** [comment]
Hello

Thanks for your mail

You are right, I didn’t understand right the url where store the hd-counter archives..

Now I can see

Many Thanks

Javier

**Comment by forrestkirby** [comment]
> Now I can see

Great that it’s working now, thanks for reporting back.

>  I didn’t understand right the url where store the hd-counter archives..

If you have a suggestion how to formulate the [installation instructions](https://github.com/forrestkirby/counter-element#installation) more clearly, please let me know.

Regards
Thomas
