### ISSUE TITLE
Feature request: add the Unit text size option

### ISSUE THREAD

**Issue by alex-revo** [forrestkirby/counter-element#17]
![image](https://user-images.githubusercontent.com/7030604/103256137-24bd2200-499d-11eb-9700-04ef2a6ccbb0.png)

Please add the unit text size option also.

**Comment by forrestkirby** [comment]
The unit text size and color are set by the same option as the number size and color. If you need to set a different font size for the unit, you can do so by adding custom CSS to the element using the selector `.el-unit`, e.g.

```css
.el-unit { font-size: 7px; }
```

Does that suit your needs?

**Comment by forrestkirby** [comment]
closed due to inactivity

**Comment by alex-revo** [comment]
Of course, I did, but for beginners it will be convenient to have an option in the settings.
Thanks!

**Comment by forrestkirby** [comment]
added with [2.3.29](https://github.com/forrestkirby/counter-element/commit/4a3d0d1c285493703b45e60801e0fd53d6926a99)
