### ISSUE TITLE
Feature request: icon option

### ISSUE THREAD

**Issue by alex-revo** [forrestkirby/counter-element#18]
![image](https://user-images.githubusercontent.com/7030604/103256664-1f60d700-499f-11eb-8138-0bbcc9e1d00a.png)

Please add the icon option to the element.
I can't create this layout now:
![image](https://user-images.githubusercontent.com/7030604/103256717-4f0fdf00-499f-11eb-97ac-87a298f2a24f.png)

**Comment by forrestkirby** [comment]
If you simply place an icon above a counter element, you should be able to create the layout indicated. Would that suffice for your use case?

![](https://content.screencast.com/users/forrestkirby/folders/YOOtheme/media/c9c0642b-21ca-467a-91d1-53c964154273/12.29.2020-13.42.png)

**Comment by forrestkirby** [comment]
closed due to inactivity

**Comment by alex-revo** [comment]
Ok, but I can't create a layout with 3 columns where icons from the left and counter from the right because the row has maximum 5 columns...
![image](https://user-images.githubusercontent.com/7030604/104887398-3e3e0200-597c-11eb-9e16-f2a9aaf9744f.png)
