### ISSUE TITLE
Overlay padding

### ISSUE THREAD

**Issue by alex-revo** [forrestkirby/counter-element#19]
I can't remove the padding between icon and counter, because the element used `uk-overlay` class without padding option like as the Panel element.

**Expected behavior**
Please add the padding option for getting control in this case (of course I know how to solve this with custom CSS rule).

**Screenshots**
![image](https://user-images.githubusercontent.com/7030604/104889527-63803f80-597f-11eb-844b-4c17e749521d.png)

**Comment by forrestkirby** [comment]
If you un-check the option *Show an animated circle*, there should be no class `uk-overlay` at all.

**Comment by forrestkirby** [comment]
closed due to inactivity

**Comment by alex-revo** [comment]
Thank you!
