### ISSUE TITLE
Counter animation wobbling

### ISSUE THREAD

**Issue by forrestkirby** [forrestkirby/counter-element#2]
Now I see another problem, when counting, the text is giggling on the second and third line with some settings and not with others.

_Originally posted by @grabit in https://github.com/forrestkirby/counter-element/issues/1#issuecomment-512341116_

**Comment by forrestkirby** [comment]
![issue-counter-2](https://user-images.githubusercontent.com/18228336/61581653-65b2d500-ab21-11e9-9a61-c69a6878a9a1.gif)

This happens if number and unit fit into one line when the counter starts because the number has only 1 digit and when there are more digits there’s not enough space for number and unit to fit into one line, then it wraps. The `max-width` is automatically set if the class `uk-position-center` is being applied which is used to position the number and text on top of the counter. 

Workarounds:

- increase the *Circle Radius*
- choose a smaller *Number Size*
- prefix the content of the unit field with `<br>` so that it always wraps
- add `.el-element .uk-position-center { max-width: none; }` to the *Advanced > CSS* field so that it’s always in one line

This behaviour will intentionally not be prohibited because this would require limiting the size options to have only predefined sizes or always wrap the content into multiple lines. Removing the `max-width` is not an option. Having a placeholder for the final number to prevent only the wobbling but not the line break could be an option but I don’t consider this a priority if feasible at all. However, suggestions are welcome.

**Comment by grabit** [comment]
Your workaround don’t work.

Look here: https://bir.grab-it.com/the-industry
--
Jean Hins 
Grab it
107 rue Coosemans - 1030 Brussels - Belgium
Phone: +32 2 737 91 11
e-mail: jean@grab-it.com

An apple a day keeps the doctor away


Le 17 juil. 2019 à 18:30, forrestkirby <notifications@github.com> a écrit :

Closed #2 <https://github.com/forrestkirby/counter-element/issues/2>.

**Comment by forrestkirby** [comment]
I was referring to the line break, but I think you are referring to the wobbling in the same line, right? As the number counts up, the width of the line changes, of course. And the wobble is visible because it’s positioned centered. But I do not consider this a bug, it’s rather by design and I am not aware of any counter that has something like a placeholder which is the only way I can think of which would prevent this (except for maybe a fixed width which is not an option). For example, the Elementor Counter element or the cf Counter for YOOtheme Pro have the same behaviour.

## HD Counter

![hd-counter](https://user-images.githubusercontent.com/18228336/61581614-ff2db700-ab20-11e9-8fac-f6d936f5359a.gif)

## Elementor Counter

![elementor-counter](https://user-images.githubusercontent.com/18228336/61581534-d35e0180-ab1f-11e9-9875-5fd959906a9e.gif)

## Cf Counter

![cf-counter](https://user-images.githubusercontent.com/18228336/61581535-d527c500-ab1f-11e9-8f12-d6ccade01131.gif)

---

Workarounds:

- set *Text Alignment* to `Right`, so only the number will change but the text should then stay in its position
- only use the *Text* field and not the *unit* field
- choose a font like *Roboto* where the numbers are of equal width

Using a starting number would not be an option.
