### ISSUE TITLE
Counters not triggering on "in view" anymore

### ISSUE THREAD

**Issue by Nuberu79** [forrestkirby/counter-element#22]
**Describe the bug**

In previous versions the counters will activate when "in view". This behaviour is lost now and they trigger "on load".

**To Reproduce**

Put a counter anywhere down in a page. When you scroll to it, it will be already completed.

**Expected behavior**

The expected behavior is the counter to start counting when it's visible to the user.

**Client (please complete the following information):**

Windows 11 / Chrome0

**Comment by forrestkirby** [comment]
please see https://github.com/forrestkirby/herzogdupont-joomla/issues/55
