### ISSUE TITLE
Not clickable

### ISSUE THREAD

**Issue by Martin511** [forrestkirby/counter-element#8]
Hello, 
the installation works and the icon is active in builder, but it is not clickable.

**Comment by forrestkirby** [comment]
Hi Martin511,

which Version of YOOtheme Pro are you using?

**Comment by Martin511** [comment]
Version 1.22.8

**Comment by forrestkirby** [comment]
The current version is already built for YOOtheme Pro 2.0.0-beta.10 (see the [changelog](https://github.com/forrestkirby/counter-element/blob/master/CHANGELOG.md)). Please try [this package (1.1.2)](https://github.com/forrestkirby/counter-element/archive/111af4e5b0d61e041838c489aed421dfadf8e09b.zip) instead. [Repository at that point in the history](https://github.com/forrestkirby/counter-element/tree/111af4e5b0d61e041838c489aed421dfadf8e09b)

**Comment by Martin511** [comment]
Thank you!
Works like a charm now!
